### PR TITLE
Added optional 'ignoreFiles' config parameter

### PR DESCRIPTION
**Pull request by dwightgunning**
The ability to specify a custom File Ignore pattern would be useful.

### CODE REVIEW

**Comment by dwightgunning** [comment]
Hi there,

I just forked and created a quick PR for a tweak I needed. If you'd like more context or adjustments to better document the change or PR, just let me know.

Regards,

Dwight

**Comment by dynamicdan** [comment]
Nice and simple. Thanks for the contribution!

**Comment by dwightgunning** [comment]
I just realised this opens up the possibility for a nasty scenario where the ".sync_data" folder ends up being included in the chokidar watch list.

I ought to fix this. Suggestions:
 1) Further PR that will concat the ignoreFiles array with "**/.sync_data/*" will ensure that the .sync_data folder is **never** watched. I don't think there'd be any situation where this folder should be watched and sync'd.
 2) Provide a mega-warning in the README.

**Comment by dynamicdan** [comment]
We might need to double check your use case. I'm guessing your IDE is saving some kind of "project" file that you want to ignore? If so then one can use this folder setup:

project/
project/records/

Where the project file is saved in project/ and the config syncs the files in the sub-folders in the project/records/ folder.

Do you have some example use cases to share?

**Comment by dwightgunning** [comment]
My preference is to rename 'records' to '.records'.

The reason for this is that I have a gulp build pipeline to generate those
records. The record files wont typically be edited directly and I won't
have them under revision control.

So a dot.filename makes sense.

**Comment by dynamicdan** [comment]
That's interesting. So you don't actually want to sync any files/fields back to the instance record? That's kind of the main point of FileSync. Are you then building some kind of archive/review system? If so, are you aware of the new --search option? Perhaps you can automate what you want to pull down as record fields to files using search without having the watcher run?

In any case, feel free to submit a new PR to add the .sync_data to the array (inc README update).

**Comment by dwightgunning** [comment]
I probably didn't explain that well. The intention is definitely to sync
with the SNOW instance. The point is that the files that are being sync'd
are actually preprocessed, minified, uglified etc. So the files to be
synchronised aren't edited by hand, they're an artifact/output of an
automated build pipeline. Therefore they don't belong under source control
and they don't need to be visible in the context of the "project".

I do need to check out the Search feature.

I'll submit another PR and update the docs.
ᐧ

--
Dwight Gunning
Twitter me: @dwightgunning <https://www.twitter.com/dwightgunning>

**Pull request merged**
